// <auto-generated />
using System;
using LanguagePractice.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LanguagePractice.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260810092223_FeaturePackSocialAuthPremium")]
    partial class FeaturePackSocialAuthPremium
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LanguagePractice.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("BanReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BannedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BannedByAdminId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PremiumExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.BanRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BanType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByAdminId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GuestSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemGenerated")
                        .HasColumnType("boolean");

                    b.Property<string>("PeerKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("RelatedReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("GuestSessionId");

                    b.HasIndex("IsActive");

                    b.HasIndex("PeerKey");

                    b.HasIndex("RelatedReportId");

                    b.HasIndex("UserId");

                    b.ToTable("BanRecords", (string)null);
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.ConversationTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TextEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("TextTr")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("ConversationTopics", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            LanguageCode = "*",
                            SortOrder = 1,
                            TextEn = "What hobby makes you lose track of time?",
                            TextTr = "Zamanı unutturan hobin nedir?"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            LanguageCode = "*",
                            SortOrder = 2,
                            TextEn = "Describe your perfect weekend.",
                            TextTr = "Mükemmel bir hafta sonunu anlat."
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            LanguageCode = "*",
                            SortOrder = 3,
                            TextEn = "What are you learning right now besides languages?",
                            TextTr = "Diller dışında şu an ne öğreniyorsun?"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            LanguageCode = "*",
                            SortOrder = 4,
                            TextEn = "Recommend a movie or series and why.",
                            TextTr = "Bir film veya dizi öner ve nedenini söyle."
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            LanguageCode = "*",
                            SortOrder = 5,
                            TextEn = "What food from your culture should everyone try?",
                            TextTr = "Kültüründen herkesin denemesi gereken yemek nedir?"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            LanguageCode = "*",
                            SortOrder = 6,
                            TextEn = "Tell a funny travel or school story.",
                            TextTr = "Komik bir seyahat veya okul hikâyesi anlat."
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            LanguageCode = "*",
                            SortOrder = 7,
                            TextEn = "What goal are you working toward this year?",
                            TextTr = "Bu yıl hangi hedefe çalışıyorsun?"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            LanguageCode = "*",
                            SortOrder = 8,
                            TextEn = "If you could live anywhere for a month, where?",
                            TextTr = "Bir ay herhangi bir yerde yaşasan nerede olurdu?"
                        });
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddresseeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeId");

                    b.HasIndex("RequesterId", "AddresseeId")
                        .IsUnique();

                    b.ToTable("Friendships", (string)null);
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.GuestSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BanExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BanReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BannedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreferredLanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("SessionToken")
                        .IsUnique();

                    b.ToTable("GuestSessions", (string)null);
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.InterestTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("InterestTags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Music",
                            IsActive = true,
                            Slug = "music",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Movies",
                            IsActive = true,
                            Slug = "movies",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Travel",
                            IsActive = true,
                            Slug = "travel",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Sports",
                            IsActive = true,
                            Slug = "sports",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Gaming",
                            IsActive = true,
                            Slug = "gaming",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Food",
                            IsActive = true,
                            Slug = "food",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Books",
                            IsActive = true,
                            Slug = "books",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Tech",
                            IsActive = true,
                            Slug = "tech",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Art",
                            IsActive = true,
                            Slug = "art",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Fashion",
                            IsActive = true,
                            Slug = "fashion",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Nature",
                            IsActive = true,
                            Slug = "nature",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 12,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Comedy",
                            IsActive = true,
                            Slug = "comedy",
                            SortOrder = 12
                        });
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "en",
                            IsActive = true,
                            Name = "English",
                            NativeName = "English"
                        },
                        new
                        {
                            Id = 2,
                            Code = "tr",
                            IsActive = true,
                            Name = "Turkish",
                            NativeName = "Türkçe"
                        },
                        new
                        {
                            Id = 3,
                            Code = "de",
                            IsActive = true,
                            Name = "German",
                            NativeName = "Deutsch"
                        },
                        new
                        {
                            Id = 4,
                            Code = "es",
                            IsActive = true,
                            Name = "Spanish",
                            NativeName = "Español"
                        },
                        new
                        {
                            Id = 5,
                            Code = "fr",
                            IsActive = true,
                            Name = "French",
                            NativeName = "Français"
                        },
                        new
                        {
                            Id = 6,
                            Code = "it",
                            IsActive = true,
                            Name = "Italian",
                            NativeName = "Italiano"
                        },
                        new
                        {
                            Id = 7,
                            Code = "ja",
                            IsActive = true,
                            Name = "Japanese",
                            NativeName = "日本語"
                        },
                        new
                        {
                            Id = 8,
                            Code = "ko",
                            IsActive = true,
                            Name = "Korean",
                            NativeName = "한국어"
                        },
                        new
                        {
                            Id = 9,
                            Code = "zh",
                            IsActive = true,
                            Name = "Chinese",
                            NativeName = "中文"
                        },
                        new
                        {
                            Id = 10,
                            Code = "hi",
                            IsActive = true,
                            Name = "Hindi",
                            NativeName = "हिन्दी"
                        },
                        new
                        {
                            Id = 11,
                            Code = "ar",
                            IsActive = true,
                            Name = "Arabic",
                            NativeName = "العربية"
                        },
                        new
                        {
                            Id = 12,
                            Code = "bn",
                            IsActive = true,
                            Name = "Bengali",
                            NativeName = "বাংলা"
                        },
                        new
                        {
                            Id = 13,
                            Code = "pt",
                            IsActive = true,
                            Name = "Portuguese",
                            NativeName = "Português"
                        },
                        new
                        {
                            Id = 14,
                            Code = "ru",
                            IsActive = true,
                            Name = "Russian",
                            NativeName = "Русский"
                        },
                        new
                        {
                            Id = 15,
                            Code = "ur",
                            IsActive = true,
                            Name = "Urdu",
                            NativeName = "اردو"
                        },
                        new
                        {
                            Id = 16,
                            Code = "id",
                            IsActive = true,
                            Name = "Indonesian",
                            NativeName = "Bahasa Indonesia"
                        },
                        new
                        {
                            Id = 17,
                            Code = "sw",
                            IsActive = true,
                            Name = "Swahili",
                            NativeName = "Kiswahili"
                        },
                        new
                        {
                            Id = 18,
                            Code = "vi",
                            IsActive = true,
                            Name = "Vietnamese",
                            NativeName = "Tiếng Việt"
                        },
                        new
                        {
                            Id = 19,
                            Code = "pl",
                            IsActive = true,
                            Name = "Polish",
                            NativeName = "Polski"
                        },
                        new
                        {
                            Id = 20,
                            Code = "nl",
                            IsActive = true,
                            Name = "Dutch",
                            NativeName = "Nederlands"
                        });
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.MatchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GuestSessionAId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GuestSessionBId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("MatchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PracticeLanguageId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("QueuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte?>("RatingByUserA")
                        .HasColumnType("smallint");

                    b.Property<byte?>("RatingByUserB")
                        .HasColumnType("smallint");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserAId")
                        .HasColumnType("text");

                    b.Property<string>("UserBId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GuestSessionAId");

                    b.HasIndex("GuestSessionBId");

                    b.HasIndex("PracticeLanguageId");

                    b.HasIndex("QueuedAtUtc");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.HasIndex("UserAId");

                    b.HasIndex("UserBId");

                    b.ToTable("MatchHistories", (string)null);
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.UserBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BlockedGuestSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("BlockedUserId")
                        .HasColumnType("text");

                    b.Property<string>("BlockerUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("BlockedUserId");

                    b.HasIndex("BlockerUserId", "BlockedGuestSessionId");

                    b.HasIndex("BlockerUserId", "BlockedUserId");

                    b.ToTable("UserBlocks", (string)null);
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.UserLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLearning")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTeaching")
                        .HasColumnType("boolean");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UserId", "LanguageId")
                        .IsUnique();

                    b.ToTable("UserLanguages", (string)null);
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("BrowserNotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Gender")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Interests")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDiscoverable")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageLevel")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("NativeLanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("PreferSharedInterests")
                        .HasColumnType("boolean");

                    b.Property<bool>("PreferSimilarLevel")
                        .HasColumnType("boolean");

                    b.Property<string>("PreferredPartnerGender")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("TargetLanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.UserReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("AutoAction")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("MatchHistoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("ReportedGuestSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReportedPeerDisplayName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ReportedPeerSocketId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ReportedUserId")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReporterGuestSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReporterIpHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ReporterUserId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolvedByAdminId")
                        .HasColumnType("text");

                    b.Property<string>("RoomId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("MatchHistoryId");

                    b.HasIndex("ReportedGuestSessionId");

                    b.HasIndex("ReportedUserId");

                    b.HasIndex("ReporterGuestSessionId");

                    b.HasIndex("ReporterUserId");

                    b.HasIndex("RoomId");

                    b.HasIndex("Status");

                    b.ToTable("UserReports", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.BanRecord", b =>
                {
                    b.HasOne("LanguagePractice.Core.Entities.GuestSession", "GuestSession")
                        .WithMany()
                        .HasForeignKey("GuestSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LanguagePractice.Core.Entities.UserReport", "RelatedReport")
                        .WithMany()
                        .HasForeignKey("RelatedReportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", "User")
                        .WithMany("BanRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("GuestSession");

                    b.Navigation("RelatedReport");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.Friendship", b =>
                {
                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", "Addressee")
                        .WithMany()
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Addressee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.MatchHistory", b =>
                {
                    b.HasOne("LanguagePractice.Core.Entities.GuestSession", "GuestSessionA")
                        .WithMany()
                        .HasForeignKey("GuestSessionAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LanguagePractice.Core.Entities.GuestSession", "GuestSessionB")
                        .WithMany()
                        .HasForeignKey("GuestSessionBId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LanguagePractice.Core.Entities.Language", "PracticeLanguage")
                        .WithMany()
                        .HasForeignKey("PracticeLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", "UserA")
                        .WithMany("MatchesAsUserA")
                        .HasForeignKey("UserAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", "UserB")
                        .WithMany("MatchesAsUserB")
                        .HasForeignKey("UserBId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("GuestSessionA");

                    b.Navigation("GuestSessionB");

                    b.Navigation("PracticeLanguage");

                    b.Navigation("UserA");

                    b.Navigation("UserB");
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.UserBlock", b =>
                {
                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", "BlockedUser")
                        .WithMany()
                        .HasForeignKey("BlockedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", "Blocker")
                        .WithMany()
                        .HasForeignKey("BlockerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockedUser");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.UserLanguage", b =>
                {
                    b.HasOne("LanguagePractice.Core.Entities.Language", "Language")
                        .WithMany("UserLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", "User")
                        .WithMany("Languages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.UserProfile", b =>
                {
                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", "User")
                        .WithOne("Profile")
                        .HasForeignKey("LanguagePractice.Core.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.UserReport", b =>
                {
                    b.HasOne("LanguagePractice.Core.Entities.MatchHistory", "MatchHistory")
                        .WithMany()
                        .HasForeignKey("MatchHistoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LanguagePractice.Core.Entities.GuestSession", "ReportedGuestSession")
                        .WithMany()
                        .HasForeignKey("ReportedGuestSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", "ReportedUser")
                        .WithMany("ReportsReceived")
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LanguagePractice.Core.Entities.GuestSession", "ReporterGuestSession")
                        .WithMany()
                        .HasForeignKey("ReporterGuestSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", "ReporterUser")
                        .WithMany()
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MatchHistory");

                    b.Navigation("ReportedGuestSession");

                    b.Navigation("ReportedUser");

                    b.Navigation("ReporterGuestSession");

                    b.Navigation("ReporterUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("BanRecords");

                    b.Navigation("Languages");

                    b.Navigation("MatchesAsUserA");

                    b.Navigation("MatchesAsUserB");

                    b.Navigation("Profile");

                    b.Navigation("ReportsReceived");
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.Language", b =>
                {
                    b.Navigation("UserLanguages");
                });
#pragma warning restore 612, 618
        }
    }
}
