// <auto-generated />
using System;
using LanguagePractice.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LanguagePractice.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.17");

            modelBuilder.Entity("LanguagePractice.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BanReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BannedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("BannedByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.BanRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BanType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GuestSessionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PeerKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RelatedReportId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("GuestSessionId");

                    b.HasIndex("IsActive");

                    b.HasIndex("PeerKey");

                    b.HasIndex("RelatedReportId");

                    b.HasIndex("UserId");

                    b.ToTable("BanRecords", (string)null);
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.GuestSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BanExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("BanReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BannedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredLanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("SessionToken")
                        .IsUnique();

                    b.ToTable("GuestSessions", (string)null);
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.InterestTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("InterestTags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Music",
                            IsActive = true,
                            Slug = "music",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Movies",
                            IsActive = true,
                            Slug = "movies",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Travel",
                            IsActive = true,
                            Slug = "travel",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Sports",
                            IsActive = true,
                            Slug = "sports",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Gaming",
                            IsActive = true,
                            Slug = "gaming",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Food",
                            IsActive = true,
                            Slug = "food",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Books",
                            IsActive = true,
                            Slug = "books",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Tech",
                            IsActive = true,
                            Slug = "tech",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Art",
                            IsActive = true,
                            Slug = "art",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Fashion",
                            IsActive = true,
                            Slug = "fashion",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Nature",
                            IsActive = true,
                            Slug = "nature",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 12,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Comedy",
                            IsActive = true,
                            Slug = "comedy",
                            SortOrder = 12
                        });
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "en",
                            IsActive = true,
                            Name = "English",
                            NativeName = "English"
                        },
                        new
                        {
                            Id = 2,
                            Code = "tr",
                            IsActive = true,
                            Name = "Turkish",
                            NativeName = "Türkçe"
                        },
                        new
                        {
                            Id = 3,
                            Code = "de",
                            IsActive = true,
                            Name = "German",
                            NativeName = "Deutsch"
                        },
                        new
                        {
                            Id = 4,
                            Code = "es",
                            IsActive = true,
                            Name = "Spanish",
                            NativeName = "Español"
                        },
                        new
                        {
                            Id = 5,
                            Code = "fr",
                            IsActive = true,
                            Name = "French",
                            NativeName = "Français"
                        },
                        new
                        {
                            Id = 6,
                            Code = "it",
                            IsActive = true,
                            Name = "Italian",
                            NativeName = "Italiano"
                        },
                        new
                        {
                            Id = 7,
                            Code = "ja",
                            IsActive = true,
                            Name = "Japanese",
                            NativeName = "日本語"
                        },
                        new
                        {
                            Id = 8,
                            Code = "ko",
                            IsActive = true,
                            Name = "Korean",
                            NativeName = "한국어"
                        },
                        new
                        {
                            Id = 9,
                            Code = "zh",
                            IsActive = true,
                            Name = "Chinese",
                            NativeName = "中文"
                        },
                        new
                        {
                            Id = 10,
                            Code = "hi",
                            IsActive = true,
                            Name = "Hindi",
                            NativeName = "हिन्दी"
                        },
                        new
                        {
                            Id = 11,
                            Code = "ar",
                            IsActive = true,
                            Name = "Arabic",
                            NativeName = "العربية"
                        },
                        new
                        {
                            Id = 12,
                            Code = "bn",
                            IsActive = true,
                            Name = "Bengali",
                            NativeName = "বাংলা"
                        },
                        new
                        {
                            Id = 13,
                            Code = "pt",
                            IsActive = true,
                            Name = "Portuguese",
                            NativeName = "Português"
                        },
                        new
                        {
                            Id = 14,
                            Code = "ru",
                            IsActive = true,
                            Name = "Russian",
                            NativeName = "Русский"
                        },
                        new
                        {
                            Id = 15,
                            Code = "ur",
                            IsActive = true,
                            Name = "Urdu",
                            NativeName = "اردو"
                        },
                        new
                        {
                            Id = 16,
                            Code = "id",
                            IsActive = true,
                            Name = "Indonesian",
                            NativeName = "Bahasa Indonesia"
                        },
                        new
                        {
                            Id = 17,
                            Code = "sw",
                            IsActive = true,
                            Name = "Swahili",
                            NativeName = "Kiswahili"
                        },
                        new
                        {
                            Id = 18,
                            Code = "vi",
                            IsActive = true,
                            Name = "Vietnamese",
                            NativeName = "Tiếng Việt"
                        },
                        new
                        {
                            Id = 19,
                            Code = "pl",
                            IsActive = true,
                            Name = "Polish",
                            NativeName = "Polski"
                        },
                        new
                        {
                            Id = 20,
                            Code = "nl",
                            IsActive = true,
                            Name = "Dutch",
                            NativeName = "Nederlands"
                        });
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.MatchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GuestSessionAId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GuestSessionBId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MatchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PracticeLanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("QueuedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte?>("RatingByUserA")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("RatingByUserB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserBId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuestSessionAId");

                    b.HasIndex("GuestSessionBId");

                    b.HasIndex("PracticeLanguageId");

                    b.HasIndex("QueuedAtUtc");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.HasIndex("UserAId");

                    b.HasIndex("UserBId");

                    b.ToTable("MatchHistories", (string)null);
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.UserLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLearning")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTeaching")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UserId", "LanguageId")
                        .IsUnique();

                    b.ToTable("UserLanguages", (string)null);
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Interests")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDiscoverable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageLevel")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("NativeLanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetLanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.UserReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("AutoAction")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MatchHistoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReportedGuestSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportedPeerDisplayName")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportedPeerSocketId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportedUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReporterGuestSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReporterIpHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReporterUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedByAdminId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("MatchHistoryId");

                    b.HasIndex("ReportedGuestSessionId");

                    b.HasIndex("ReportedUserId");

                    b.HasIndex("ReporterGuestSessionId");

                    b.HasIndex("ReporterUserId");

                    b.HasIndex("RoomId");

                    b.HasIndex("Status");

                    b.ToTable("UserReports", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.BanRecord", b =>
                {
                    b.HasOne("LanguagePractice.Core.Entities.GuestSession", "GuestSession")
                        .WithMany()
                        .HasForeignKey("GuestSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LanguagePractice.Core.Entities.UserReport", "RelatedReport")
                        .WithMany()
                        .HasForeignKey("RelatedReportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", "User")
                        .WithMany("BanRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("GuestSession");

                    b.Navigation("RelatedReport");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.MatchHistory", b =>
                {
                    b.HasOne("LanguagePractice.Core.Entities.GuestSession", "GuestSessionA")
                        .WithMany()
                        .HasForeignKey("GuestSessionAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LanguagePractice.Core.Entities.GuestSession", "GuestSessionB")
                        .WithMany()
                        .HasForeignKey("GuestSessionBId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LanguagePractice.Core.Entities.Language", "PracticeLanguage")
                        .WithMany()
                        .HasForeignKey("PracticeLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", "UserA")
                        .WithMany("MatchesAsUserA")
                        .HasForeignKey("UserAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", "UserB")
                        .WithMany("MatchesAsUserB")
                        .HasForeignKey("UserBId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("GuestSessionA");

                    b.Navigation("GuestSessionB");

                    b.Navigation("PracticeLanguage");

                    b.Navigation("UserA");

                    b.Navigation("UserB");
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.UserLanguage", b =>
                {
                    b.HasOne("LanguagePractice.Core.Entities.Language", "Language")
                        .WithMany("UserLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", "User")
                        .WithMany("Languages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.UserProfile", b =>
                {
                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", "User")
                        .WithOne("Profile")
                        .HasForeignKey("LanguagePractice.Core.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.UserReport", b =>
                {
                    b.HasOne("LanguagePractice.Core.Entities.MatchHistory", "MatchHistory")
                        .WithMany()
                        .HasForeignKey("MatchHistoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LanguagePractice.Core.Entities.GuestSession", "ReportedGuestSession")
                        .WithMany()
                        .HasForeignKey("ReportedGuestSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", "ReportedUser")
                        .WithMany("ReportsReceived")
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LanguagePractice.Core.Entities.GuestSession", "ReporterGuestSession")
                        .WithMany()
                        .HasForeignKey("ReporterGuestSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", "ReporterUser")
                        .WithMany()
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MatchHistory");

                    b.Navigation("ReportedGuestSession");

                    b.Navigation("ReportedUser");

                    b.Navigation("ReporterGuestSession");

                    b.Navigation("ReporterUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LanguagePractice.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("BanRecords");

                    b.Navigation("Languages");

                    b.Navigation("MatchesAsUserA");

                    b.Navigation("MatchesAsUserB");

                    b.Navigation("Profile");

                    b.Navigation("ReportsReceived");
                });

            modelBuilder.Entity("LanguagePractice.Core.Entities.Language", b =>
                {
                    b.Navigation("UserLanguages");
                });
#pragma warning restore 612, 618
        }
    }
}
